---
- name: Copy file with owner and permissions
  command: "virt-clone --original {{ image_original }} --name {{ vm_name }} --file /var/lib/libvirt/images/{{ vm_name }}.qcow2"
  changed_when: True


- name: Customize image files for networking
  shell: "virt-customize -a /var/lib/libvirt/images/{{ vm_name }}.qcow2 --run-command 'echo \"{{ netplan_configuration }}\" > {{ netplan_config_file }} '"
  changed_when: True

- name: Start VM
  command: "virsh start {{ vm_name }}"
  when: nostartvm is undefined